language: perl
perl:
  - '5.24'
  - '5.22'
distro: trusty
sudo: required
before_install:
  - sudo apt-get install libglade2-dev libgnomecanvas2-dev

  # Here as well as cpanfile because of dependency problems if not installed before Gnome2::Canvas
  - cpanm --notest ExtUtils::Depends ExtUtils::PkgConfig Glib Gtk2

  # Here as well as cpanfile because -v stops travis from timing out and killing the build
  # (and -v for the whole install produces a ridiculously large log)
  #  Could adapt approach used in https://github.com/shawnlaffan/bd_travis_experiment
  #  or install libgdal-dev via apt-get (if it can be located)
  - cpanm -v Geo::GDAL
env:
  - BD_NO_TEST_GUI=1
script: prove -l
# blocklist
branches:
  except:
  - ppm
